runtime: python39

instance_class: F2

env_variables:
  DATABASE_URL: "your-database-url"
  JWT_SECRET: "your-secret-key"

automatic_scaling:
  min_instances: 1
  max_instances: 3

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
