version: "3.11"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://test01:test01@35.201.178.208:5432/test01
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chloe
      POSTGRES_DB: leave_attendance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: