
# This workflow is triggered on pushes to the main branch
name: Push to Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Push to GCP Artifact Registry
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      # FIXME
      # Run unit tests
      # - name: Run Unit Tests
      #   run: |
      #     pytest --cov=app tests/

      # Build Docker image
      # - name: Build Docker Image
      #   run: |
      #     docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/leave-attendance-backend:latest .

      # # Authenticate with GCP
      # - name: Authenticate with GCP
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # # Configure Docker for GCP
      # - name: Configure Docker for GCP
      #   run: |
      #     gcloud auth configure-docker

      # # Push Docker image to GCP Artifact Registry
      # - name: Push Docker Image to GCP Artifact Registry
      #   run: |
      #     docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/leave-attendance-backend:latest

      # # Deploy to Google App Engine
      # - name: Deploy to GCP
      #   uses: google-github-actions/deploy-appengine@v1
      #   with:
      #     credentials: ${{ secrets.GCP_CREDENTIALS }}
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     deliverables: app.yaml